#' Two sequences of random numbers of length 100 generated by human participants.
#'
#' @format A data frame with 100 rows and 2 columns:
#' \describe{
#'   \item{sequence_one}{first sequence of random numbers}
#'   \item{sequence_two}{second sequence of random numbers}
#'}
#' @source
#' Taken from Evans (1978; see reference below),
#' \url{https://doi.org/10.3758/BF03329617}.
#'
#' @references
#' Evans, F.J. Monitoring attention deployment by random number generation:
#' An index to measure subjective randomness.
#' Bull. Psychon. Soc. 12, 35–38 (1978).
#' \url{https://doi.org/10.3758/BF03329617}
"evans1978"
